# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'XFCrystalKitExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XFCrystalKitExample
    pod 'XFSettings'

  target 'XFCrystalKitExampleTests' do
    # inherit! :search_paths
    # Pods for testing
  end

  target 'XFCrystalKitExampleUITests' do
    # inherit! :search_paths
    # Pods for testing
  end

end
